# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Mar 13 16:15:25 2011
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setCursor(QtCore.Qt.ArrowCursor)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget_3 = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget_3.setGeometry(QtCore.QRect(400, 300, 390, 250))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_27 = QtGui.QWidget()
        self.tab_27.setObjectName("tab_27")
        self.console = QtGui.QTextEdit(self.tab_27)
        self.console.setGeometry(QtCore.QRect(0, 0, 381, 211))
        self.console.setFrameShape(QtGui.QFrame.StyledPanel)
        self.console.setFrameShadow(QtGui.QFrame.Plain)
        self.console.setLineWidth(0)
        self.console.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.console.setUndoRedoEnabled(False)
        self.console.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.console.setReadOnly(True)
        self.console.setAcceptRichText(False)
        self.console.setObjectName("console")
        self.tabWidget_3.addTab(self.tab_27, "")
        self.tab_28 = QtGui.QWidget()
        self.tab_28.setObjectName("tab_28")
        self.tabWidget_3.addTab(self.tab_28, "")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 300, 385, 250))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_29 = QtGui.QWidget()
        self.tab_29.setObjectName("tab_29")
        self.steering = QtGui.QSlider(self.tab_29)
        self.steering.setGeometry(QtCore.QRect(110, 140, 261, 20))
        self.steering.setSizeIncrement(QtCore.QSize(0, 0))
        self.steering.setMinimum(-30)
        self.steering.setMaximum(30)
        self.steering.setProperty("value", 0)
        self.steering.setOrientation(QtCore.Qt.Horizontal)
        self.steering.setObjectName("steering")
        self.label_57 = QtGui.QLabel(self.tab_29)
        self.label_57.setGeometry(QtCore.QRect(40, 180, 41, 17))
        self.label_57.setObjectName("label_57")
        self.stop = QtGui.QPushButton(self.tab_29)
        self.stop.setGeometry(QtCore.QRect(110, 10, 261, 101))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../avidgui_resources/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.stop.setIcon(icon)
        self.stop.setObjectName("stop")
        self.speed = QtGui.QSlider(self.tab_29)
        self.speed.setGeometry(QtCore.QRect(50, 10, 20, 161))
        self.speed.setMaximum(100)
        self.speed.setOrientation(QtCore.Qt.Vertical)
        self.speed.setObjectName("speed")
        self.label_58 = QtGui.QLabel(self.tab_29)
        self.label_58.setGeometry(QtCore.QRect(210, 180, 61, 17))
        self.label_58.setObjectName("label_58")
        self.tabWidget.addTab(self.tab_29, "")
        self.tab_30 = QtGui.QWidget()
        self.tab_30.setObjectName("tab_30")
        self.layoutWidget_10 = QtGui.QWidget(self.tab_30)
        self.layoutWidget_10.setGeometry(QtCore.QRect(10, 6, 361, 211))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.formLayout_18 = QtGui.QFormLayout(self.layoutWidget_10)
        self.formLayout_18.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_18.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_18.setObjectName("formLayout_18")
        self.label_59 = QtGui.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.formLayout_18.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_59)
        self.latitude = QtGui.QLineEdit(self.layoutWidget_10)
        self.latitude.setMaximumSize(QtCore.QSize(16777143, 16777215))
        self.latitude.setObjectName("latitude")
        self.formLayout_18.setWidget(0, QtGui.QFormLayout.FieldRole, self.latitude)
        self.label_60 = QtGui.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.formLayout_18.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_60)
        self.longitude = QtGui.QLineEdit(self.layoutWidget_10)
        self.longitude.setObjectName("longitude")
        self.formLayout_18.setWidget(1, QtGui.QFormLayout.FieldRole, self.longitude)
        self.set_destination = QtGui.QPushButton(self.layoutWidget_10)
        self.set_destination.setObjectName("set_destination")
        self.formLayout_18.setWidget(2, QtGui.QFormLayout.FieldRole, self.set_destination)
        self.lookup = QtGui.QPushButton(self.layoutWidget_10)
        self.lookup.setObjectName("lookup")
        self.formLayout_18.setWidget(5, QtGui.QFormLayout.FieldRole, self.lookup)
        self.address = QtGui.QLineEdit(self.layoutWidget_10)
        self.address.setObjectName("address")
        self.formLayout_18.setWidget(4, QtGui.QFormLayout.FieldRole, self.address)
        self.label_2 = QtGui.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_18.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_18.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem)
        self.tabWidget.addTab(self.tab_30, "")
        self.tabWidget_2 = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 385, 280))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_31 = QtGui.QWidget()
        self.tab_31.setObjectName("tab_31")
        self.formLayoutWidget_5 = QtGui.QWidget(self.tab_31)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 361, 221))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_19 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_19.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_19.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_19.setObjectName("formLayout_19")
        self.label_61 = QtGui.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_61.setObjectName("label_61")
        self.formLayout_19.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_61)
        self.ip = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.ip.setObjectName("ip")
        self.formLayout_19.setWidget(0, QtGui.QFormLayout.FieldRole, self.ip)
        self.label_62 = QtGui.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_62.setObjectName("label_62")
        self.formLayout_19.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_62)
        self.port = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.port.setObjectName("port")
        self.formLayout_19.setWidget(1, QtGui.QFormLayout.FieldRole, self.port)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_19.setItem(2, QtGui.QFormLayout.LabelRole, spacerItem1)
        self.disconnect = QtGui.QPushButton(self.formLayoutWidget_5)
        self.disconnect.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnect.sizePolicy().hasHeightForWidth())
        self.disconnect.setSizePolicy(sizePolicy)
        self.disconnect.setAutoFillBackground(False)
        self.disconnect.setObjectName("disconnect")
        self.formLayout_19.setWidget(3, QtGui.QFormLayout.LabelRole, self.disconnect)
        self.connect = QtGui.QPushButton(self.formLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect.sizePolicy().hasHeightForWidth())
        self.connect.setSizePolicy(sizePolicy)
        self.connect.setObjectName("connect")
        self.formLayout_19.setWidget(3, QtGui.QFormLayout.FieldRole, self.connect)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_19.setItem(4, QtGui.QFormLayout.FieldRole, spacerItem2)
        self.label_63 = QtGui.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.formLayout_19.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_63)
        self.connection_status_label = QtGui.QLabel(self.formLayoutWidget_5)
        self.connection_status_label.setObjectName("connection_status_label")
        self.formLayout_19.setWidget(5, QtGui.QFormLayout.FieldRole, self.connection_status_label)
        self.label = QtGui.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_19.setWidget(7, QtGui.QFormLayout.LabelRole, self.label)
        self.show_sends = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.show_sends.setChecked(True)
        self.show_sends.setObjectName("show_sends")
        self.formLayout_19.setWidget(7, QtGui.QFormLayout.FieldRole, self.show_sends)
        self.show_receives = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.show_receives.setChecked(True)
        self.show_receives.setObjectName("show_receives")
        self.formLayout_19.setWidget(8, QtGui.QFormLayout.FieldRole, self.show_receives)
        self.show_dbw = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.show_dbw.setChecked(True)
        self.show_dbw.setObjectName("show_dbw")
        self.formLayout_19.setWidget(9, QtGui.QFormLayout.FieldRole, self.show_dbw)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_19.setItem(6, QtGui.QFormLayout.FieldRole, spacerItem3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_19.setItem(10, QtGui.QFormLayout.FieldRole, spacerItem4)
        self.tabWidget_2.addTab(self.tab_31, "")
        self.tab_32 = QtGui.QWidget()
        self.tab_32.setObjectName("tab_32")
        self.layoutWidget_11 = QtGui.QWidget(self.tab_32)
        self.layoutWidget_11.setGeometry(QtCore.QRect(30, 0, 321, 251))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_20 = QtGui.QFormLayout()
        self.formLayout_20.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_20.setVerticalSpacing(9)
        self.formLayout_20.setObjectName("formLayout_20")
        self.label_64 = QtGui.QLabel(self.layoutWidget_11)
        self.label_64.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_64.setSizeIncrement(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.formLayout_20.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_64)
        self.label_65 = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_65.setFont(font)
        self.label_65.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_65.setObjectName("label_65")
        self.formLayout_20.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_65)
        self.label_66 = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_66.setFont(font)
        self.label_66.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_66.setObjectName("label_66")
        self.formLayout_20.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_66)
        self.label_67 = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_67.setFont(font)
        self.label_67.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_67.setObjectName("label_67")
        self.formLayout_20.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_67)
        self.label_68 = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_68.setFont(font)
        self.label_68.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_68.setObjectName("label_68")
        self.formLayout_20.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_68)
        self.label_69 = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_69.setFont(font)
        self.label_69.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_69.setObjectName("label_69")
        self.formLayout_20.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_69)
        self.horizontalLayout_5.addLayout(self.formLayout_20)
        self.formLayout_21 = QtGui.QFormLayout()
        self.formLayout_21.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_21.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_21.setVerticalSpacing(9)
        self.formLayout_21.setObjectName("formLayout_21")
        self.status_latitude = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.status_latitude.setFont(font)
        self.status_latitude.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_latitude.setObjectName("status_latitude")
        self.formLayout_21.setWidget(4, QtGui.QFormLayout.FieldRole, self.status_latitude)
        self.status_longitude = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.status_longitude.setFont(font)
        self.status_longitude.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_longitude.setObjectName("status_longitude")
        self.formLayout_21.setWidget(5, QtGui.QFormLayout.FieldRole, self.status_longitude)
        self.status_wheel = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.status_wheel.setFont(font)
        self.status_wheel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_wheel.setObjectName("status_wheel")
        self.formLayout_21.setWidget(3, QtGui.QFormLayout.FieldRole, self.status_wheel)
        self.status_compass = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.status_compass.setFont(font)
        self.status_compass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_compass.setObjectName("status_compass")
        self.formLayout_21.setWidget(2, QtGui.QFormLayout.FieldRole, self.status_compass)
        self.status_brake = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.status_brake.setFont(font)
        self.status_brake.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_brake.setObjectName("status_brake")
        self.formLayout_21.setWidget(1, QtGui.QFormLayout.FieldRole, self.status_brake)
        self.status_speed = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.status_speed.setFont(font)
        self.status_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_speed.setObjectName("status_speed")
        self.formLayout_21.setWidget(0, QtGui.QFormLayout.FieldRole, self.status_speed)
        self.horizontalLayout_5.addLayout(self.formLayout_21)
        self.tabWidget_2.addTab(self.tab_32, "")
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(400, 10, 390, 280))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.map = QtWebKit.QWebView(self.frame)
        self.map.setGeometry(QtCore.QRect(1, 1, 388, 278))
        self.map.setUrl(QtCore.QUrl("http://maps.google.com/maps?ie=UTF8&ll=35.300215,-120.660439&spn=0.00641,0.017982&z=17&output=embed"))
        self.map.setObjectName("map")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_about = QtGui.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_map = QtGui.QAction(MainWindow)
        self.action_map.setObjectName("action_map")
        self.menuFile.addAction(self.action_map)
        self.menuFile.addAction(self.action_exit)
        self.menuAbout.addAction(self.action_about)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Golf Cart Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_27), QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_28), QtGui.QApplication.translate("MainWindow", "SICK Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setToolTip(QtGui.QApplication.translate("MainWindow", "Drive Control", None, QtGui.QApplication.UnicodeUTF8))
        self.steering.setToolTip(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(QtGui.QApplication.translate("MainWindow", "Stop && Center", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "Steering", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_29), QtGui.QApplication.translate("MainWindow", "Drive By Wire", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_29), QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Drive By Wire Controls</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("MainWindow", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MainWindow", "                     Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.set_destination.setText(QtGui.QApplication.translate("MainWindow", "Set Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.lookup.setText(QtGui.QApplication.translate("MainWindow", "Lookup Lat/Lon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_30), QtGui.QApplication.translate("MainWindow", "Autonomous GPS ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_30), QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Autonomous GPS Driving</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("MainWindow", "IP", None, QtGui.QApplication.UnicodeUTF8))
        self.ip.setInputMask(QtGui.QApplication.translate("MainWindow", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.ip.setText(QtGui.QApplication.translate("MainWindow", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("MainWindow", "                                 Port", None, QtGui.QApplication.UnicodeUTF8))
        self.port.setInputMask(QtGui.QApplication.translate("MainWindow", "00000 ; ", None, QtGui.QApplication.UnicodeUTF8))
        self.port.setText(QtGui.QApplication.translate("MainWindow", "50000 ", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnect.setText(QtGui.QApplication.translate("MainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.connect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("MainWindow", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.connection_status_label.setText(QtGui.QApplication.translate("MainWindow", "Disconnected", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Console Options", None, QtGui.QApplication.UnicodeUTF8))
        self.show_sends.setText(QtGui.QApplication.translate("MainWindow", "Show sends", None, QtGui.QApplication.UnicodeUTF8))
        self.show_receives.setText(QtGui.QApplication.translate("MainWindow", "Show receives", None, QtGui.QApplication.UnicodeUTF8))
        self.show_dbw.setText(QtGui.QApplication.translate("MainWindow", "Show DBW sends", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_31), QtGui.QApplication.translate("MainWindow", "Server Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("MainWindow", "Brake %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("MainWindow", "Compass", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MainWindow", "Wheel Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("MainWindow", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("MainWindow", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.status_latitude.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.status_longitude.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.status_wheel.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.status_compass.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.status_brake.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.status_speed.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_32), QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_map.setText(QtGui.QApplication.translate("MainWindow", "Reload Map", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
