/* Auto-generated by genmsg_cpp for file /home/ros/cp-capstone-autogolfcart/golfcart_encoder/msg/GolfcartEncoder.msg */
#ifndef GOLFCART_ENCODER_MESSAGE_GOLFCARTENCODER_H
#define GOLFCART_ENCODER_MESSAGE_GOLFCARTENCODER_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "roslib/Header.h"

namespace golfcart_encoder
{
template <class ContainerAllocator>
struct GolfcartEncoder_ : public ros::Message
{
  typedef GolfcartEncoder_<ContainerAllocator> Type;

  GolfcartEncoder_()
  : header()
  , ticks(0)
  , speed(0.0)
  , heading(0.0)
  {
  }

  GolfcartEncoder_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , ticks(0)
  , speed(0.0)
  , heading(0.0)
  {
  }

  typedef  ::roslib::Header_<ContainerAllocator>  _header_type;
   ::roslib::Header_<ContainerAllocator>  header;

  typedef uint32_t _ticks_type;
  uint32_t ticks;

  typedef float _speed_type;
  float speed;

  typedef float _heading_type;
  float heading;


private:
  static const char* __s_getDataType_() { return "golfcart_encoder/GolfcartEncoder"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "18c718a4e49012651be1786ed08daf09"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
uint32 ticks\n\
float32 speed\n\
float32 heading\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, ticks);
    ros::serialization::serialize(stream, speed);
    ros::serialization::serialize(stream, heading);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, ticks);
    ros::serialization::deserialize(stream, speed);
    ros::serialization::deserialize(stream, heading);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(ticks);
    size += ros::serialization::serializationLength(speed);
    size += ros::serialization::serializationLength(heading);
    return size;
  }

  typedef boost::shared_ptr< ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator>  const> ConstPtr;
}; // struct GolfcartEncoder
typedef  ::golfcart_encoder::GolfcartEncoder_<std::allocator<void> > GolfcartEncoder;

typedef boost::shared_ptr< ::golfcart_encoder::GolfcartEncoder> GolfcartEncoderPtr;
typedef boost::shared_ptr< ::golfcart_encoder::GolfcartEncoder const> GolfcartEncoderConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace golfcart_encoder

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "18c718a4e49012651be1786ed08daf09";
  }

  static const char* value(const  ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x18c718a4e4901265ULL;
  static const uint64_t static_value2 = 0x1be1786ed08daf09ULL;
};

template<class ContainerAllocator>
struct DataType< ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "golfcart_encoder/GolfcartEncoder";
  }

  static const char* value(const  ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint32 ticks\n\
float32 speed\n\
float32 heading\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.ticks);
    stream.next(m.speed);
    stream.next(m.heading);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GolfcartEncoder_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::golfcart_encoder::GolfcartEncoder_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::roslib::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ticks: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ticks);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
  }
};


} // namespace message_operations
} // namespace ros

#endif // GOLFCART_ENCODER_MESSAGE_GOLFCARTENCODER_H

